import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1776178651434 implements MigrationInterface {
    name = 'InitialMigration1776178651434'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_departments_name" ON "departments" ("name") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cilents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_d23db17a7f2cf57e96474578941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_users" ("project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_from_date" TIMESTAMP DEFAULT now(), "assigned_to_date" TIMESTAMP DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_4d392d4703ae37be0cc9a253175" PRIMARY KEY ("project_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "timesheet_statuses" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_4e59f2f804fc9a1f0fdfb530e55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timesheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "weekNumber" integer NOT NULL, "year" integer NOT NULL, "date" TIMESTAMP NOT NULL, "hours" double precision NOT NULL DEFAULT '0', "submitted_at" TIMESTAMP DEFAULT now(), "note" text, "approved_at" TIMESTAMP, "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "projectIdId" uuid, "userIdId" uuid, "status" character varying, "approved_by" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_1dc280b68c9353ecce41a34be71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_statuses" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_b0ca0748cbeddc71d6bf76c2fa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text, "allocated_hours" integer NOT NULL DEFAULT '0', "completed_at" TIMESTAMP, "started_at" TIMESTAMP DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "client_id" uuid, "manager_id" uuid, "status" character varying, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_projects_client_id" ON "projects" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_manager_id" ON "projects" ("manager_id") `);
        await queryRunner.query(`CREATE TABLE "leave_statuses" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_eb14d081bc2847ed4e700d6b63e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_types" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_359223e0755d19711813cd07394" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_balances" ("user_id" uuid NOT NULL, "leave_type_id" character varying NOT NULL, "year" integer NOT NULL, "total_leaves" integer NOT NULL, "per_month_leaves_used" integer NOT NULL, "disable_months" character varying NOT NULL, "leaves_used" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "leave_status_id" character varying, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_c96727e7b6f0420af2593ca7549" PRIMARY KEY ("user_id", "leave_type_id", "year"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" text, "email" text, "password_hash" text, "designation" text, "status" "public"."users_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "refreshToken" text, "role_id" character varying, "manager_id" uuid, "department_id" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_role_id" ON "users" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_designation" ON "users" ("designation") `);
        await queryRunner.query(`CREATE INDEX "idx_users_manager_id" ON "users" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_department_id" ON "users" ("department_id") `);
        await queryRunner.query(`CREATE TABLE "otp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "expired_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leaves" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "leave" double precision, "reason" text, "applied_on" TIMESTAMP, "approved_on" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "leave_type_id" character varying, "leave_status_id" character varying, "approved_by" uuid, "created_by" uuid, "updated_by" uuid, CONSTRAINT "PK_4153ec7270da3d07efd2e11e2a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_e4fb15c173042ccd356099f69f6" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_2a517743a9cd9c4afdef36ec033" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_747b580d73db0ad78963d78b076" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cilents" ADD CONSTRAINT "FK_a23c02244ce5f11d468ba828121" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cilents" ADD CONSTRAINT "FK_76287e6b49f1a0ab277a7071698" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_users" ADD CONSTRAINT "FK_1cd910b13f600795316505623cd" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_users" ADD CONSTRAINT "FK_6be3042b14e8024b255efd1aedf" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_users" ADD CONSTRAINT "FK_3a53b25fef9b1ac81501a2816a5" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_users" ADD CONSTRAINT "FK_076af26ee5a7bbcce3f77bfddfb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_statuses" ADD CONSTRAINT "FK_5d56e133b2549ddf4f3b75f647f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_statuses" ADD CONSTRAINT "FK_3f6559e360115c1ad7392457db9" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_5577d5d7511338d20c9f74fa39a" FOREIGN KEY ("projectIdId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_c61bf5fa845a1ca44fc4ec3d339" FOREIGN KEY ("userIdId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_5323e538db5a38387d8aa302a4f" FOREIGN KEY ("status") REFERENCES "timesheet_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_6cb3dbdf496045a9c1e5172c0dc" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_12aea6e2736fad11ec99c495e78" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_dfdbac8cd85069198e22be36838" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_e890b44a3b88da8046e3fb43c03" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_e87f4a4a85cb9932938c695a692" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_statuses" ADD CONSTRAINT "FK_0a7df2f206b0c38a2b15f22bb30" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_statuses" ADD CONSTRAINT "FK_52c7ad861ed5df7f9fc73f967c9" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_ca29f959102228649e714827478" FOREIGN KEY ("client_id") REFERENCES "cilents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_87bd52575ded2be008b89dd7b21" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_a27865a7be17886e3088f4a6509" FOREIGN KEY ("status") REFERENCES "project_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_458ce18ebdb792c80257bc96678" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_statuses" ADD CONSTRAINT "FK_797dc0f572a2ccc590a249ce16d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_statuses" ADD CONSTRAINT "FK_1bd316e293e72adcc57ceea8d59" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_types" ADD CONSTRAINT "FK_022f185730e3132ffa8de8b7f28" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_types" ADD CONSTRAINT "FK_18da0efa3572f95228e5cd34aa2" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_99c2efbd8185cc9da9fbec88338" FOREIGN KEY ("leave_status_id") REFERENCES "leave_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_c6831adbffdef9243012c99090b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_8159b525aff2e34c6ff492fab00" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_d64da0a991d2f4d23d86031530c" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_89ffc3253557b60d4d979ffe50c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_fba2d8e029689aa8fea98e53c91" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f32b1cb14a9920477bcfd63df2c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_b75c92ef36f432fe68ec300a7d4" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_258d028d322ea3b856bf9f12f25" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_e15ff77626160e8f7d75c046f12" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_60e30d9063247bfe25b0e6ad30f" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_80500bfd86d628c5e9fdcb49fac" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_f434fa2bee32673ad01d59ea810" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_b3d6fc3831e1bddeb035ddc6f37" FOREIGN KEY ("leave_status_id") REFERENCES "leave_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_9b68981ebf771160d0f6f78ad0f" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_e9e539b5df10d1a044ed5916fd3" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_8496c124f5cecbad1ad6cc75b9d" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_8496c124f5cecbad1ad6cc75b9d"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_e9e539b5df10d1a044ed5916fd3"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_9b68981ebf771160d0f6f78ad0f"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_b3d6fc3831e1bddeb035ddc6f37"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_f434fa2bee32673ad01d59ea810"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_80500bfd86d628c5e9fdcb49fac"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_60e30d9063247bfe25b0e6ad30f"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_e15ff77626160e8f7d75c046f12"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_258d028d322ea3b856bf9f12f25"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_b75c92ef36f432fe68ec300a7d4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f32b1cb14a9920477bcfd63df2c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_fba2d8e029689aa8fea98e53c91"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_89ffc3253557b60d4d979ffe50c"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_d64da0a991d2f4d23d86031530c"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_8159b525aff2e34c6ff492fab00"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_c6831adbffdef9243012c99090b"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_99c2efbd8185cc9da9fbec88338"`);
        await queryRunner.query(`ALTER TABLE "leave_types" DROP CONSTRAINT "FK_18da0efa3572f95228e5cd34aa2"`);
        await queryRunner.query(`ALTER TABLE "leave_types" DROP CONSTRAINT "FK_022f185730e3132ffa8de8b7f28"`);
        await queryRunner.query(`ALTER TABLE "leave_statuses" DROP CONSTRAINT "FK_1bd316e293e72adcc57ceea8d59"`);
        await queryRunner.query(`ALTER TABLE "leave_statuses" DROP CONSTRAINT "FK_797dc0f572a2ccc590a249ce16d"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_458ce18ebdb792c80257bc96678"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_a27865a7be17886e3088f4a6509"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_87bd52575ded2be008b89dd7b21"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_ca29f959102228649e714827478"`);
        await queryRunner.query(`ALTER TABLE "project_statuses" DROP CONSTRAINT "FK_52c7ad861ed5df7f9fc73f967c9"`);
        await queryRunner.query(`ALTER TABLE "project_statuses" DROP CONSTRAINT "FK_0a7df2f206b0c38a2b15f22bb30"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_e87f4a4a85cb9932938c695a692"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_e890b44a3b88da8046e3fb43c03"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_dfdbac8cd85069198e22be36838"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_12aea6e2736fad11ec99c495e78"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_6cb3dbdf496045a9c1e5172c0dc"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_5323e538db5a38387d8aa302a4f"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_c61bf5fa845a1ca44fc4ec3d339"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_5577d5d7511338d20c9f74fa39a"`);
        await queryRunner.query(`ALTER TABLE "timesheet_statuses" DROP CONSTRAINT "FK_3f6559e360115c1ad7392457db9"`);
        await queryRunner.query(`ALTER TABLE "timesheet_statuses" DROP CONSTRAINT "FK_5d56e133b2549ddf4f3b75f647f"`);
        await queryRunner.query(`ALTER TABLE "project_users" DROP CONSTRAINT "FK_076af26ee5a7bbcce3f77bfddfb"`);
        await queryRunner.query(`ALTER TABLE "project_users" DROP CONSTRAINT "FK_3a53b25fef9b1ac81501a2816a5"`);
        await queryRunner.query(`ALTER TABLE "project_users" DROP CONSTRAINT "FK_6be3042b14e8024b255efd1aedf"`);
        await queryRunner.query(`ALTER TABLE "project_users" DROP CONSTRAINT "FK_1cd910b13f600795316505623cd"`);
        await queryRunner.query(`ALTER TABLE "cilents" DROP CONSTRAINT "FK_76287e6b49f1a0ab277a7071698"`);
        await queryRunner.query(`ALTER TABLE "cilents" DROP CONSTRAINT "FK_a23c02244ce5f11d468ba828121"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_747b580d73db0ad78963d78b076"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_2a517743a9cd9c4afdef36ec033"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_e4fb15c173042ccd356099f69f6"`);
        await queryRunner.query(`DROP TABLE "leaves"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_department_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_manager_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_designation"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role_id"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "leave_balances"`);
        await queryRunner.query(`DROP TABLE "leave_types"`);
        await queryRunner.query(`DROP TABLE "leave_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_manager_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_client_id"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "project_statuses"`);
        await queryRunner.query(`DROP TABLE "timesheets"`);
        await queryRunner.query(`DROP TABLE "timesheet_statuses"`);
        await queryRunner.query(`DROP TABLE "project_users"`);
        await queryRunner.query(`DROP TABLE "cilents"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_departments_name"`);
        await queryRunner.query(`DROP TABLE "departments"`);
    }

}
